enum ErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  NOT_FOUND = "NOT_FOUND",
  INVALID_OPERATION = "INVALID_OPERATION",
  PARAMETER_MISSING = "PARAMETER_MISSING",
  HEADER_MISSING = "HEADER_MISSING",
  AUTH_FAILED = "AUTH_FAILED",
  SIGNER_ALREADY_EXISTS = "SIGNER_ALREADY_EXISTS",
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND",
  OAUTH_CLIENT_NOT_FOUND = "OAUTH_CLIENT_NOT_FOUND",
}

export default ErrorCode;
